### ISSUE TITLE
Redirection handling

### ISSUE THREAD

**Issue by sebnow** [bloglovin/bletcd#3]
`bletcd` currently doesn't handle redirects. If a 3xx redirection status code is returned, `bletcd` considers it an error.

https://github.com/bloglovin/bletcd/blob/943826c12504ba53559e777fe142ebf96ada94f9/index.js#L136

**Comment by hugowetterberg** [comment]
Thank you, redirects to leader are now handled correctly in 2.1.0 and newer versions.
